config/routes.rb
Testapp3::Application.routes.draw do
  devise_for :users

    root :to => 'staticpage#index'
    resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  # attr_accessible :title, :body
 	attr_accessible :hour, :emotion, :learned, :image
	mount_uploader :image, ImageUploader

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

has_many :pics

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_filter :authenticate_user!, :only => [:new, :create]


def index
	@pics = Pic.all
end



def new
	@pic = Pic.new
	end



def create
	@pics = current_user.pics.create(params[:pic])
	redirect_to pics_path
end

end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.meetup.com/Learn-to-Code-NYC/events/140935392/">FireHoseNYC App</a>
    by Parvaz
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://railstutorial.org/">RoR Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to 'FireHoseNYC', root_path, :class => 'brand' %>
      
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      <ul class="nav">
      	
      	<li>
		<%= link_to 'The App', pics_path %>
		</li>
		
		<li>
		<%= link_to 'New Image', new_pic_path %>
		</li>
        </ul>


		<ul class="nav pull-right">

		<% if user_signed_in? %>
		
		<li>
		<%= link_to current_user.email, '#' %>
		</li>

		<li>
		<%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete' %>
		</li>

		<% else %>
      	<li>
		<%= link_to 'Sign Up', new_user_registration_path %>
		</li>
		
      	<li>
		<%= link_to 'Sign In', new_user_session_path %>
		</li>
		
		<% end %>
	    </ul>




		<!--<ul class="nav pull-right">
        <form class="navbar-search">
  			<input type="text" class="search-query" placeholder="Search">
	    </form>
		</ul>
		-->
    </div>
    </div>
  </div>
</div>
		<% if notice.present? %>
		<p class="notice"><%= notice %></p>
		<%end%>

		<% if alert.present? %>
       	<p class="alert"><%= alert %></p>
       	<%end%>

<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pics/index.html.erb
<div class="custom-font">
	<h2 class="cool-font-medium">This is how it all went down ...</h2>

	<div class="container cool-font-tiny">
		<div class="row">
			<%	@pics.each do |pic| %>
				<div class="boxy span3">
					<h2> 
						Hour <%= pic.hour %>
					</h2>
					
					<div>
						<%= image_tag pic.image.to_s	%>
					</div>

					<p>
					<%= pic.emotion %>
					</p>

					<p>
					I learned that
					<%= pic.learned %>
					</p>

					<% if pic.user.present? %>
						<p>
						Email: <%= pic.user.email %>
						</p>
					<% end%>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/pics/new.html.erb
<div class="custom-font">
<h2 class="cool-font-medium">Upload your stuff here ...</h2>
<div class="custom-font-mini boxy span5 offset3 text-center">

<%= simple_form_for @pic do |f| %>
	<%= f.input :hour, :label=> 'Which Hour', :labelfont=> "cool-font-medium", :placeholder=> 'Enter the hour' 		%>
	<%= f.input :image, :label=> 'Upload A Pic', :as=> :file 		%>
	<%= f.input :emotion, :label=> 'How did you feel?', :placeholder=> 'Happy, Stoked, Angry, Pissed'	%>
	<%= f.input :learned, :label=> 'What did you learn?', :placeholder=> 'CSSA, HTML5, or whatever you like!', :input_html=> {:rows=> '5'}	%>
</br>
	<%= link_to 'Cancel', pics_path, :class => 'btn btn-danger btn-large' %>
	<%= submit_tag 'Submit', :class => 'btn btn-danger btn-large' 	%>
	
<% end %>
</div>
</div>

app/views/staticpage/index.html.erb
<div class="text-center">

	<h1 class="cool-font-big text-center"> Welcome to 
		<a href="http://icahn.mssm.edu/research/programs/narc/">Parvaz's</a>
		FireHoseNYC App </h1>


	<h2 class="cool-font-tiny"> Here, You'll see my pics, how I felt, and what I learned during the FireHoseNYC</h2>

</br></br></br></br></br></br></br>
</br></br></br></br></br></br>
</br></br></br></br></br></br></br>

<%= link_to 'You can upload too...', new_pic_path, :class => 'btn btn-danger btn-large' %>
</br></br>
</div>
</div>